---
title: "Erez Braun"
---

The potential for cellular systems to improvise was convincingly demonstrated in yeast in a set of experiments from the group of Erez Braun. In short, Braun and colleagues engineered a completely novel challenge for yeast to overcome by placing the genes required to synthesize an essential amino acid (histidine) under a promoter that yeast evolved to respond to the sugar galactose [Stolovicki2006-sd](../references/stolovicki2006-sd.qmd). In its evolutionary past, yeast preferred to use glucose over galactose as an energy source and so in the presence of glucose it would turn off the galactose promoter. Thus yeast grown in glucose with this Gal-His operon would face a challenge, to turn off the galactose promoter would prevent the synthesis of an essential amino acid. Braun and colleagues then showed that yeast are able to learn how to solve this problem and rapidly adapt their gene expression to de-repress the promoter and produce the necessary histidine. They checked that this adaptation was not due to genetic mutations and further showed through transcriptomics that different populations of yeast arrived at unique solutions to the challenge.

Summary of contributions

## Related references

| Reference | Title |
| --- | --- |
| [Stolovicki2006-sd](../references/stolovicki2006-sd.qmd) | Synthetic gene recruitment reveals adaptive reprogramming of gene regulation in yeast |
| [Moore2014-xa](../references/moore2014-xa.qmd) | Induced mutations in yeast cell populations adapting to an unforeseen challenge |
| [Katzir2012-ci](../references/katzir2012-ci.qmd) | Cellular plasticity enables adaptation to unforeseen cell-cycle rewiring challenges |
