---
title: "Shelley D Copley"
---

[Shelley Copley](https://www.colorado.edu/mcdb/shelley-copley)

A promiscuous enzyme is one who that is involved in more than one reaction. The Copley lab has shown that when the secondary function of a promiscuous enzyme is made essential in *Escherichia coli,* the gene encoding the ‘weak-link’ enzyme is often amplified, but mutations improving the now essential activity occurred only rarely. 

> *Most adaptive mutations occurred elsewhere in the genome. Some mutations increase expression of the enzyme upstream of the weak-link enzyme, pushing material through the dysfunctional metabolic pathway. Others enhance production of a co-substrate for a downstream enzyme, thereby pulling material through the pathway. Most of these latter mutations are detrimental in wild-type E. coli, and thus would require reversion or compensation once a sufficient new activity has evolved*
> 

In addition to the findings of [Daniel Jarosz](daniel-jarosz.qmd) that synonymous mutations have similar fitness effects to non-synonymous mutations in yeast, Shelley Copley has found that synonymous mutations play an important role in fitness in the context of her “weak link” enzyme systems. In *Salmonella enterica, she* found that two synonymous mutations increased the growth rate by 41 and 67% .

Summary of contributions

## Related references

| Reference | Title |
| --- | --- |
| [Morgenthaler2019-za](../references/morgenthaler2019-za.qmd) | Mutations that improve efficiency of a weak-link enzyme are rare compared to adaptive mutations elsewhere in the genome |
| [Kristofich2018-kd](../references/kristofich2018-kd.qmd) | Synonymous mutations make dramatic contributions to fitness when growth is limited by a weak-link enzyme |
| [Khanal2015-sl](../references/khanal2015-sl.qmd) | Differential effects of a mutation on the normal and promiscuous activities of orthologs: implications for natural and directed evolution |
| [Copley2007-xo](../references/copley2007-xo.qmd) | The origin of the RNA world: co-evolution of genes and metabolism |
